Deploying project on Docker: docker-compose, Dockerfile, .env. probat…
PawelSzepelewicz/NewRepository pull request #13
Opened 2021-08-16 11:57 UTC by PawelSzepelewicz

Deploying on Docker

2021-08-16 12:14 UTC, allofapiece requested changes

2021-08-16 12:14 UTC, allofapiece commented on docker/Dockerfile
> +EXPOSE 8084
Не уверен что это нужно, если ты используешь докер компоуз
Попробуй удалить EXPOSE

2021-08-16 12:14 UTC, allofapiece commented on src/main/resources/static/account.js
> +        const host = "http://localhost:8084"
А если я локально у себя буду запускать и у меня бэк на другом порту находится, или например, если ты зальёшь этот код в облако, где уже будет не localhost,  а реальный домен твой фронт не будет работать
Ты вроде в application.properties определяешь текущий хост типа `server.host` наверно.
Определи эту константу значением из проперти `server.host`

2021-08-16 12:14 UTC, allofapiece commented on src/main/resources/static/account.js
> +                    window.location = 'http://localhost:8084/login'
А тут почему не используется host?

2021-08-17 14:25 UTC, allofapiece requested changes

2021-08-17 14:25 UTC, allofapiece commented on src/main/resources/static/main.js
> +        const host = ${server.host}
??

2021-08-17 14:25 UTC, allofapiece commented on src/main/resources/templates/confirmation.html
> +        const host = [[${server.host}]];
Может просто host?

2021-08-17 14:29 UTC, PawelSzepelewicz commented on src/main/resources/static/main.js
> +        const host = ${server.host}
точно, забыл убрать

2021-08-17 14:29 UTC, PawelSzepelewicz commented on src/main/resources/templates/confirmation.html
> +        const host = [[${server.host}]];
тоже забыл убрать, здесь вообще не нужен хост

2021-08-24 09:58 UTC, merged