Kafka
PawelSzepelewicz/NewRepository pull request #15
Opened 2021-08-30 10:01 UTC by PawelSzepelewicz

Branch for task "Microservices"

2021-09-03 17:29 UTC, VolodjaGuzh requested changes

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/configurations/WebSecurityConfig.kt
> +    companion object {
basically, companion object declaration is made at the bottom of the class

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/configurations/WebSecurityConfig.kt
> +open class WebSecurityConfig(
do you really need open class here?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/configurations/WebSecurityConfig.kt
> +        http.csrf().disable()
why did you disabled csrf?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/core/dto/LogDto.kt
> +    var username: String? = null,
why have you made `NotNull` fields nullable? please fix this

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/core/entity/VerificationToken.kt
> +    @Column(name = "token")
it is not needed to set column name if it is the same as the property

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/core/entity/VerificationToken.kt
> +    @Column(name = "expiryDate")
why do you have different columns name formats, e.g. `user_name`, `expiryDate`? it is better to make it formalazied accross th application, in that case it will be also not necessary to set `Column` annotation

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/core/enums/Current.kt
> +enum class Current(var value: String) {
why do you need this single value enum?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/event/RegistrationListener.kt
> +        event.user?.let {
what is the purpose to move this to a separate private method? did you reuse it somewhere?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/repository/UsersRepository.kt
> +    fun findByUsername(username: String?): User?
did you accept null values here? if not, make the parameter not nullable, the same is true for the whole application

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/CustomUserDetailsService.kt
> +open class CustomUserDetailsService(
why have you made it open?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/CustomUserDetailsService.kt
> +                it.username!!,
please get rid of the `!!` operators

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/CustomUserDetailsService.kt
> +            ).let { userDto ->
use `also` instead of `let` when you need to perform some action and return the same object
please read the [documentation](https://kotlinlang.org/docs/scope-functions.html)

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/KafkaProducerServiceImpl.kt
> +        LogDto().apply {
```
        LogDto().apply {
            this.username = username
            this.action = action
            val cal = Calendar.getInstance()
            this.subject = subject
            this.actionTime = Timestamp(cal.time.time)
        }.let { kafkaTemplate.send("spring-audit", it) }
```

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/TokenServiceImpl.kt
> +            val confirmationUrl = host + endpoint + token
`val confirmationUrl = "${host}/confirmation?token=${token}"`

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/TokenServiceImpl.kt
> +            val subject = "Registration Confirmation"
a good point to move it to translation properties

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/TokenServiceImpl.kt
> +            val messageText = "message.registrationSuccess"
there is no need to set it o a separate variable

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/TokenServiceImpl.kt
> +        tokenRepository.getByUser(user).let {
```
        tokenRepository.getByUser(user)?.let {
            tokenRepository.delete(it)
        }
```

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/UsersServiceImpl.kt
> +        mutableSetOf(roleService.getRoleByRoleName(Roles.USER.role))
probably `roles=`?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/UsersServiceImpl.kt
> +        if (username != null) {
what should be if the username will be null?

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/UsersServiceImpl.kt
> +        if (name == Current.CURRENT.value) {
some strange logic here, it should be reworked or even removed.
first of all, you should throw the exception immediately and not catch
second, you do not need to call details service many times, just do it once and use the username from context. there is no need to compare the username with CURRENT constant

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/CustomUserDetailsService.kt
> +        SecurityContextHolder.getContext().authentication.apply {
```
        SecurityContextHolder.getContext().authentication?.run {
            if (ANONYMOUS == name) {
                throw ForbiddenException("{forbidden}")
            }
            name
        } ?: throw ForbiddenException("{forbidden}")
```

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/validation/annotation/UniqueNewEmail.kt
> +annotation class UniqueNewEmail(
you do not need two different annotations. it could be just one `UniqueEmail` annotation but with two implementations

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/validation/validator/NameValidator.kt
> +        if (name == null) {
please format the code

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/validation/validator/NewEmailValidator.kt
> +        usersService.checkUniqueNewEmail(info.email!!, info.id).let {
apply

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/validation/validator/NewNameValidator.kt
> +        usersService.checkUniqueNewName(info.username!!, info.id).let {
apply

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/test/kotlin/com/example/probation/controller/UsersControllerTest.kt
> +        mockMvc.perform(MockMvcRequestBuilders.get("http://localhost:8080/users/current"))
it looks not correct with the 8080 port defined with the random port configuration

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/test/kotlin/com/example/probation/repository/RoleRepositoryTest.kt
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
you do not need the whole spring boot context for the repository tests

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/test/kotlin/com/example/probation/controller/UsersControllerTest.kt
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
also in such cases, it is always better to have some abstract common class with the configuration annotations set and extend this class by the test classes

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/test/kotlin/com/example/probation/service/UsersServiceImplTest.kt
> +                wrongToken
please format the code

2021-09-03 17:29 UTC, VolodjaGuzh commented on src/test/kotlin/com/example/probation/ProbationApplicationTests.kt
> +	fun contextLoads() {
please remove empty tests

2021-09-03 17:56 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/UsersServiceImpl.kt
> +        getUserById(id).username.let {
could be:
```
        getUserById(id).run {
            newName == username || !checkUsernameExistence(username)
        }
```

2021-09-03 17:59 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/UsersServiceImpl.kt
> +            getUserById(userId).let {
```
            getUserById(userId).apply {
               id = user.id
               username = user.username
               description = user.description
               email = user.email
            }.let { usersRepository.save(it) }
```

2021-09-13 13:25 UTC, PawelSzepelewicz commented on src/main/kotlin/com/example/probation/configurations/WebSecurityConfig.kt
> +        http.csrf().disable()
dor ajax queries

2021-09-16 18:05 UTC, VolodjaGuzh commented on src/main/kotlin/com/example/probation/service/impl/UsersServiceImpl.kt
> +            it.username?.let { name -> kafkaService.send(Actions.REGISTERED.action, name, currentUsername) }
it looks like a duplicated event. user register itself?

2021-09-22 12:55 UTC, VolodjaGuzh approved these changes

2021-09-22 13:01 UTC, merged